package popup;

import javax.swing.ImageIcon;

/**
 *
 * @author melisa_duro
 */
public class Information_popUp extends javax.swing.JFrame {

    
    String CustomHeader;
    String CustomMessage;
    String Tool;
    String option;

    String ErrorLog;

    String botonPulsado = "";


    public Information_popUp(String Header, String Message, String thisTool, String optionPopUp) {
        initComponents();
        
        option = optionPopUp;

        if (option.equalsIgnoreCase("CLOSE_MT")) {

            Tool = thisTool;
            
            Yes_Button.setVisible(true);
            No_Button.setVisible(true);

            CustomHeader = Header;
            CustomMessage = Message;

            this.setVisible(false);
            this.setAlwaysOnTop(false);
            
        } else if (option.equalsIgnoreCase("CLOSE_MT_CONTROL_PROCESS")) {

            Tool = thisTool;
            
            Yes_Button.setVisible(true);
            No_Button.setVisible(true);

            CustomHeader = Header;
            CustomMessage = Message;

            this.setVisible(false);
            this.setAlwaysOnTop(false);
            
        } else if (option.equalsIgnoreCase("INTERACTIVE_USER")) {
            Tool = thisTool;

            Yes_Button.setVisible(true);
            No_Button.setVisible(true);

            CustomHeader = Header;
            CustomMessage = Message;

            this.setVisible(false);
            this.setAlwaysOnTop(false);
        } else if (option.equalsIgnoreCase("WAIT")) {
            this.setVisible(false);

            this.setAlwaysOnTop(false);

            Yes_Button.setVisible(false);
            No_Button.setVisible(false);

            CustomHeader = Header;
        } else if (option.equalsIgnoreCase("INFORMATION")) {
            Yes_Button.setVisible(false);
            No_Button.setVisible(false);

            this.setVisible(false);
            this.setAlwaysOnTop(false);

            CustomHeader = Header;
            CustomMessage = Message;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        button2 = new java.awt.Button();
        Cerrar_popUpInfo = new java.awt.Button();
        No_Button = new java.awt.Button();
        Cerrar_popUpInfo1 = new java.awt.Button();
        Header_popUpInfo = new javax.swing.JLabel();
        Yes_Button = new java.awt.Button();
        CustomMessage_popUpInfo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        button2.setBackground(new java.awt.Color(255, 255, 255));
        button2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button2.setForeground(new java.awt.Color(208, 30, 28));
        button2.setLabel("YES");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        Cerrar_popUpInfo.setBackground(new java.awt.Color(255, 255, 255));
        Cerrar_popUpInfo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Cerrar_popUpInfo.setForeground(new java.awt.Color(0, 0, 153));
        Cerrar_popUpInfo.setLabel("X");
        Cerrar_popUpInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_popUpInfoActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar_popUpInfo);
        Cerrar_popUpInfo.setBounds(480, 10, 24, 20);

        No_Button.setBackground(new java.awt.Color(255, 255, 255));
        No_Button.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        No_Button.setForeground(new java.awt.Color(0, 0, 153));
        No_Button.setLabel("NO");
        No_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(No_Button);
        No_Button.setBounds(400, 220, 57, 24);

        Cerrar_popUpInfo1.setBackground(new java.awt.Color(255, 255, 255));
        Cerrar_popUpInfo1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Cerrar_popUpInfo1.setForeground(new java.awt.Color(228, 24, 30));
        Cerrar_popUpInfo1.setLabel("X");
        Cerrar_popUpInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_popUpInfo1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar_popUpInfo1);
        Cerrar_popUpInfo1.setBounds(480, 10, 24, 20);

        Header_popUpInfo.setBackground(new java.awt.Color(192, 222, 237));
        Header_popUpInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Header_popUpInfo.setForeground(new java.awt.Color(255, 255, 255));
        Header_popUpInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header_popUpInfo.setText("INFORMATION");
        Header_popUpInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null));
        Header_popUpInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Header_popUpInfo.setOpaque(true);
        getContentPane().add(Header_popUpInfo);
        Header_popUpInfo.setBounds(0, 0, 520, 30);

        Yes_Button.setBackground(new java.awt.Color(255, 255, 255));
        Yes_Button.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Yes_Button.setForeground(new java.awt.Color(0, 0, 153));
        Yes_Button.setLabel("YES");
        Yes_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Yes_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Yes_Button);
        Yes_Button.setBounds(70, 220, 57, 24);

        CustomMessage_popUpInfo.setBackground(new java.awt.Color(245, 245, 245));
        CustomMessage_popUpInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomMessage_popUpInfo.setForeground(new java.awt.Color(102, 102, 102));
        CustomMessage_popUpInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomMessage_popUpInfo.setText("Mensaje de Ejemplo");
        CustomMessage_popUpInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CustomMessage_popUpInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CustomMessage_popUpInfo.setOpaque(true);
        getContentPane().add(CustomMessage_popUpInfo);
        CustomMessage_popUpInfo.setBounds(0, 30, 520, 240);

        setSize(new java.awt.Dimension(519, 269));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cerrar_popUpInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_popUpInfoActionPerformed

        this.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_Cerrar_popUpInfoActionPerformed

    private void Cerrar_popUpInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_popUpInfo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cerrar_popUpInfo1ActionPerformed

    private void No_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_ButtonActionPerformed
        if (option.equalsIgnoreCase("INTERACTIVE_USER")) {
            botonPulsado = "NO";
            this.setVisible(false);
        } else {
            this.setVisible(false);
        }

    }//GEN-LAST:event_No_ButtonActionPerformed

    private void Yes_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Yes_ButtonActionPerformed
        // TODO add your handling code here:
        if (option.equalsIgnoreCase("INTERACTIVE_USER")) {
            botonPulsado = "YES";
            this.setVisible(false);
        } else if (option.equalsIgnoreCase("CLOSE_MT") || option.equalsIgnoreCase("CLOSE_MT_CONTROL_PROCESS")) {
            System.exit(0);
        }

    }//GEN-LAST:event_Yes_ButtonActionPerformed

    public void showPopUp() {

        Header_popUpInfo.setText(CustomHeader);
        CustomMessage_popUpInfo.setText(CustomMessage);

        Cerrar_popUpInfo.setVisible(true);

        this.setVisible(true);
    }

    public void showPopUp_WAIT() {

        Header_popUpInfo.setText(CustomHeader);
        CustomMessage_popUpInfo.setText("");

        ImageIcon imageIcon = null;
        imageIcon = new ImageIcon(this.getClass().getClassLoader().getResource("/main/java/images/loading.gif"));
        CustomMessage_popUpInfo.setIcon(imageIcon);

        Cerrar_popUpInfo.setVisible(false);
        this.setVisible(true);
    }

    public void showPopUp_EXIT() {

        Header_popUpInfo.setText(CustomHeader);
        CustomMessage_popUpInfo.setText(CustomMessage);

        Cerrar_popUpInfo.setVisible(true);

        this.setVisible(true);
    }

    public String getBotonPulsado() {
        return botonPulsado;
    }

    public void setBotonPulsado(String botonPulsado) {
        this.botonPulsado = botonPulsado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information_popUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information_popUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information_popUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information_popUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Information_popUp("INFO", "pepe y juan","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Cerrar_popUpInfo;
    private java.awt.Button Cerrar_popUpInfo1;
    private javax.swing.JLabel CustomMessage_popUpInfo;
    private javax.swing.JLabel Header_popUpInfo;
    private java.awt.Button No_Button;
    private java.awt.Button Yes_Button;
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
